import { CatchErrorFunc } from "../utility/CatchErrorFunc";
import {Request, Response, NextFunction} from 'express';


export const getAvailableFood = CatchErrorFunc(async(req: Request, res: Response) => {
    
});


export const getTopRestaurants = CatchErrorFunc(async (req:Request, res:Response) => {

});

export const getFoodIn30Min = CatchErrorFunc(async (req:Request, res:Response) => {
    
});

export const searchForFood = CatchErrorFunc(async (req:Request, res:Response) => {

});
  
export const getRestaurantById = CatchErrorFunc(async (req:Request, res:Response) => {

});
  